name: Deploy

on: [push]

jobs:
  publish:
    if: github.repository == 'atmtools/arts'
    runs-on: ubuntu-latest
    name: Build and publish Python wheels.
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: PyPI release
        continue-on-error: true
        uses: ./actions/pypi
        with:
          pypi_access: ${{secrets.pypi_access}}
